In [1]:
import pandas as pd

In [6]:
import matplotlib.pyplot as plt

In [7]:
import numpy as np

In [8]:
dataset=pd.read_csv('D:\\pywork\\pyproject\\sippython\\50_Startups.csv')

In [9]:
dataset

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [10]:
x=dataset.iloc[:,:-1].values ###independent columns

In [11]:
x

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 127716.82, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 110594.11, 229160.95, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [93863.75, 127320.38, 249839.44, 'Florida'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16, 114175.79, 29491

0    1          2          3          4
0   0.0  1.0  165349.20  136897.80  471784.10
1   0.0  0.0  162597.70  151377.59  443898.53
2   1.0  0.0  153441.51  101145.55  407934.54
3   0.0  1.0  144372.41  118671.85  383199.62
4   1.0  0.0  142107.34   91391.77  366168.42
5   0.0  1.0  131876.90   99814.71  362861.36
6   0.0  0.0  134615.46  147198.87  127716.82
7   1.0  0.0  130298.13  145530.06  323876.68
8   0.0  1.0  120542.52  148718.95  311613.29
9   0.0  0.0  123334.88  108679.17  304981.62
10  1.0  0.0  101913.08  110594.11  229160.95
11  0.0  0.0  100671.96   91790.61  249744.55
12  1.0  0.0   93863.75  127320.38  249839.44
13  0.0  0.0   91992.39  135495.07  252664.93
14  1.0  0.0  119943.24  156547.42  256512.92
15  0.0  1.0  114523.61  122616.84  261776.23
16  0.0  0.0   78013.11  121597.55  264346.06
17  0.0  1.0   94657.16  145077.58  282574.31
18  1.0  0.0   91749.16  114175.79  294919.57
19  0.0  1.0   86419.70  153514.11       0.00
20  0.0  0.0   76253.86  113867.30  298664.47
21  0.0  1.0   78389.47  153773.43  299737.29
22  1.0  0.0   73994.56  122782.75  303319.26
23  1.0  0.0   67532.53  105751.03  304768.73
24  0.0  1.0   77044.01   99281.34  140574.81
25  0.0  0.0   64664.71  139553.16  137962.62
26  1.0  0.0   75328.87  144135.98  134050.07
27  0.0  1.0   72107.60  127864.55  353183.81
28  1.0  0.0   66051.52  182645.56  118148.20
29  0.0  1.0   65605.48  153032.06  107138.38
30  1.0  0.0   61994.48  115641.28   91131.24
31  0.0  1.0   61136.38  152701.92   88218.23
32  0.0  0.0   63408.86  129219.61   46085.25
33  1.0  0.0   55493.95  103057.49  214634.81
34  0.0  0.0   46426.07  157693.92  210797.67
35  0.0  1.0   46014.02   85047.44  205517.64
36  1.0  0.0   28663.76  127056.21  201126.82
37  0.0  0.0   44069.95   51283.14  197029.42
38  0.0  1.0   20229.59   65947.93  185265.10
39  0.0  0.0   38558.51   82982.09  174999.30
40  0.0  0.0   28754.33  118546.05  172795.67
41  1.0  0.0   27892.92   84710.77  164470.71
42  0.0  0.0   23640.93   96189.63  148001.11
43  0.0  1.0   15505.73  127382.30   35534.17
44  0.0  0.0   22177.74  154806.14   28334.72
45  0.0  1.0    1000.23  124153.04    1903.93
46  1.0  0.0    1315.46  115816.21  297114.46
47  0.0  0.0       0.00  135426.92       0.00
48  0.0  1.0     542.05   51743.15       0.00
49  0.0  0.0       0.00  116983.80   45173.06

In [12]:
y=dataset.iloc[:,4].values ##dependent column

In [13]:
y

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
       141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
       124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
       108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
        99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
        90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
        71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
        35673.41,  14681.4 ])

0
0   192261.83
1   191792.06
2   191050.39
3   182901.99
4   166187.94
5   156991.12
6   156122.51
7   155752.60
8   152211.77
9   149759.96
10  146121.95
11  144259.40
12  141585.52
13  134307.35
14  132602.65
15  129917.04
16  126992.93
17  125370.37
18  124266.90
19  122776.86
20  118474.03
21  111313.02
22  110352.25
23  108733.99
24  108552.04
25  107404.34
26  105733.54
27  105008.31
28  103282.38
29  101004.64
30   99937.59
31   97483.56
32   97427.84
33   96778.92
34   96712.80
35   96479.51
36   90708.19
37   89949.14
38   81229.06
39   81005.76
40   78239.91
41   77798.83
42   71498.49
43   69758.98
44   65200.33
45   64926.08
46   49490.75
47   42559.73
48   35673.41
49   14681.40

In [14]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [15]:
labelencoder=LabelEncoder()

In [16]:
x[:,3]=labelencoder.fit_transform(x[:,3])

In [17]:
onehotencoder=OneHotEncoder(categorical_features=[3])

In [18]:
x=onehotencoder.fit_transform(x).toarray()

C:\Users\aa\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\aa\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [19]:
x

array([[0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.6534920e+05,
        1.3689780e+05, 4.7178410e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.6259770e+05,
        1.5137759e+05, 4.4389853e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.5344151e+05,
        1.0114555e+05, 4.0793454e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.4437241e+05,
        1.1867185e+05, 3.8319962e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.4210734e+05,
        9.1391770e+04, 3.6616842e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.3187690e+05,
        9.9814710e+04, 3.6286136e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.3461546e+05,
        1.4719887e+05, 1.2771682e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.3029813e+05,
        1.4553006e+05, 3.2387668e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.2054252e+05,
        1.4871895e+05, 3.1161329e+05],
       [1.0000000e+00, 0.0000000e+00,

In [20]:
x=x[:,1:] ###avoiding the dummy variable

In [21]:
x

array([[0.0000000e+00, 1.0000000e+00, 1.6534920e+05, 1.3689780e+05,
        4.7178410e+05],
       [0.0000000e+00, 0.0000000e+00, 1.6259770e+05, 1.5137759e+05,
        4.4389853e+05],
       [1.0000000e+00, 0.0000000e+00, 1.5344151e+05, 1.0114555e+05,
        4.0793454e+05],
       [0.0000000e+00, 1.0000000e+00, 1.4437241e+05, 1.1867185e+05,
        3.8319962e+05],
       [1.0000000e+00, 0.0000000e+00, 1.4210734e+05, 9.1391770e+04,
        3.6616842e+05],
       [0.0000000e+00, 1.0000000e+00, 1.3187690e+05, 9.9814710e+04,
        3.6286136e+05],
       [0.0000000e+00, 0.0000000e+00, 1.3461546e+05, 1.4719887e+05,
        1.2771682e+05],
       [1.0000000e+00, 0.0000000e+00, 1.3029813e+05, 1.4553006e+05,
        3.2387668e+05],
       [0.0000000e+00, 1.0000000e+00, 1.2054252e+05, 1.4871895e+05,
        3.1161329e+05],
       [0.0000000e+00, 0.0000000e+00, 1.2333488e+05, 1.0867917e+05,
        3.0498162e+05],
       [1.0000000e+00, 0.0000000e+00, 1.0191308e+05, 1.1059411e+05,
        2.29

In [26]:
from sklearn.model_selection import train_test_split

In [57]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [29]:
from sklearn.linear_model import LinearRegression

In [30]:
regressor=LinearRegression()

In [31]:
regressor.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [55]:
y_pred =pd.DataFrame(regressor.predict(x_test),columns=['y_pred_test'])

In [56]:
y_pred

y_pred_test
0  103015.201598
1  132582.277608
2  132447.738452
3   71976.098513
4  178537.482211
5  116161.242302
6   67851.692097
7   98791.733747
8  113969.435330
9  167921.065696

In [75]:
y_testname=pd.DataFrame(y_test,columns=['y_actual'])

In [76]:
y_testname

y_actual
0  103282.38
1  144259.40
2  146121.95
3   77798.83
4  191050.39
5  105008.31
6   81229.06
7   97483.56
8  110352.25
9  166187.94

In [85]:
y_testname['y_test_predicted'] = y_pred['y_pred_test']

In [87]:
y_testname

RecursionError: maximum recursion depth exceeded in __instancecheck__

In [ ]:
y_testname.plot()

In [81]:
y_testname

y_actual  y_test_predicted
0  103282.38     103015.201598
1  144259.40     132582.277608
2  146121.95     132447.738452
3   77798.83      71976.098513
4  191050.39     178537.482211
5  105008.31     116161.242302
6   81229.06      67851.692097
7   97483.56      98791.733747
8  110352.25     113969.435330
9  166187.94     167921.065696

NameError: name 'y_pred_train' is not defined

In [60]:
y_train

array([ 96778.92,  96479.51, 105733.54,  96712.8 , 124266.9 , 155752.6 ,
       132602.65,  64926.08,  35673.41, 101004.64, 129917.04,  99937.59,
        97427.84, 126992.93,  71498.49, 118474.03,  69758.98, 152211.77,
       134307.35, 107404.34, 156991.12, 125370.37,  78239.91,  14681.4 ,
       191792.06, 141585.52,  89949.14, 108552.04, 156122.51, 108733.99,
        90708.19, 111313.02, 122776.86, 149759.96,  81005.76,  49490.75,
       182901.99, 192261.83,  42559.73,  65200.33])

In [61]:
y_test

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94])

In [64]:
x_train

0    1          2          3          4
0   1.0  0.0   55493.95  103057.49  214634.81
1   0.0  1.0   46014.02   85047.44  205517.64
2   1.0  0.0   75328.87  144135.98  134050.07
3   0.0  0.0   46426.07  157693.92  210797.67
4   1.0  0.0   91749.16  114175.79  294919.57
5   1.0  0.0  130298.13  145530.06  323876.68
6   1.0  0.0  119943.24  156547.42  256512.92
7   0.0  1.0    1000.23  124153.04    1903.93
8   0.0  1.0     542.05   51743.15       0.00
9   0.0  1.0   65605.48  153032.06  107138.38
10  0.0  1.0  114523.61  122616.84  261776.23
11  1.0  0.0   61994.48  115641.28   91131.24
12  0.0  0.0   63408.86  129219.61   46085.25
13  0.0  0.0   78013.11  121597.55  264346.06
14  0.0  0.0   23640.93   96189.63  148001.11
15  0.0  0.0   76253.86  113867.30  298664.47
16  0.0  1.0   15505.73  127382.30   35534.17
17  0.0  1.0  120542.52  148718.95  311613.29
18  0.0  0.0   91992.39  135495.07  252664.93
19  0.0  0.0   64664.71  139553.16  137962.62
20  0.0  1.0  131876.90   99814.71  362861.36
21  0.0  1.0   94657.16  145077.58  282574.31
22  0.0  0.0   28754.33  118546.05  172795.67
23  0.0  0.0       0.00  116983.80   45173.06
24  0.0  0.0  162597.70  151377.59  443898.53
25  1.0  0.0   93863.75  127320.38  249839.44
26  0.0  0.0   44069.95   51283.14  197029.42
27  0.0  1.0   77044.01   99281.34  140574.81
28  0.0  0.0  134615.46  147198.87  127716.82
29  1.0  0.0   67532.53  105751.03  304768.73
30  1.0  0.0   28663.76  127056.21  201126.82
31  0.0  1.0   78389.47  153773.43  299737.29
32  0.0  1.0   86419.70  153514.11       0.00
33  0.0  0.0  123334.88  108679.17  304981.62
34  0.0  0.0   38558.51   82982.09  174999.30
35  1.0  0.0    1315.46  115816.21  297114.46
36  0.0  1.0  144372.41  118671.85  383199.62
37  0.0  1.0  165349.20  136897.80  471784.10
38  0.0  0.0       0.00  135426.92       0.00
39  0.0  0.0   22177.74  154806.14   28334.72

ValueError: Expected 2D array, got 1D array instead:
array=[103282.38 144259.4  146121.95  77798.83 191050.39 105008.31  81229.06
  97483.56 110352.25 166187.94].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.